### ISSUE TITLE
запуск inserts.py вилітає з помилкою:

### ISSUE THREAD

**Issue by alvasnet** [vromanuk/films_api#1]
~/flask-materials/films_api$ pipenv run python src/inserts.py
Traceback (most recent call last):
File "src/inserts.py", line 3, in <module>
from src import db
ModuleNotFoundError: No module named 'src'

**Comment by vromanuk** [comment]
Здравствуйте, хотелось немного больше деталей: хотя бы структуру вашего проекта, как вариант сходу - вы запускаете команду не с корня приложения.

15 квітня 2021, 16:11:21, від alvasnet ***@***.***>:



~/flask-materials/films_api$ pipenv run python src/inserts.py
Traceback (most recent call last):
File "src/inserts.py", line 3, in 
from src import db
ModuleNotFoundError: No module named 'src'

**Comment by alvasnet** [comment]
Це ваш проект з https://itvdn.com/ru/video/flask/flask-restful-api Пряме посилання:
https://itvdn.blob.core.windows.net/materials/flask-materials.zip?sv=2018-03-28&sr=b&sig=7L2ihqy9kO9gAgRQ2xEiMGk9xClerTq5KyDKu1VA5zA%3D&st=2021-04-15T14%3A48%3A21Z&se=2021-04-15T15%3A23%3A21Z&sp=rl
В другому відео ви запускаєте цей скріпт щоб заповнити таблицю films
P. S. В атачі мій проект
[films_api.zip](https://github.com/vromanuk/films_api/files/6319164/films_api.zip)

**Comment by vromanuk** [comment]
Да, я понимаю) но это не означает, что у вас такая же структура, как у меня) и плюс, прежний ответ валидный, проверьте папку, с котором запускаете эту команду

**Comment by alvasnet** [comment]
Я приатачив свій проект вище https://github.com/vromanuk/films_api/files/6319164/films_api.zip
Можете запустити у себе мій src/inserts.py?

**Comment by alvasnet** [comment]
Я запускаю команду з ~/flask-materials/films_api
films_api це корінь мого app. Структура папок і файлів на малюнку нижче
![2021-04-16](https://user-images.githubusercontent.com/19414833/114983781-b2177a00-9e99-11eb-950f-552929da2118.png)

**Comment by vromanuk** [comment]
Попробуйте заменить использование src внутри inserts, на . "from . import db" настройте относительные импорты, vscode должен подсказать

16 квітня 2021, 09:54:42, від alvasnet ***@***.***>:



Я запускаю команду з ~/flask-materials/films_api
films_api це корінь мого app. Структура папок і файлів на малюнку нижче

**Comment by alvasnet** [comment]
Знайшов таку пораду https://stackoverflow.com/questions/8013170/how-to-import-a-module-from-a-folder-next-to-the-current-folder
```
import sys, os

sys.path.insert(0,
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from src import db
from src.models import Film

del sys.path[0]
```
Нічого не зрозумів, але спрацювало

**Comment by vromanuk** [comment]
Ну это прям хак) смотрите, нужно понимать, что из-за разных ОС у вас IDE может по-разному определять пути, поэтому внутри файла он может не видеть папку src. 

16 квітня 2021, 19:18:31, від alvasnet ***@***.***>:



Знайшов таку пораду https://stackoverflow.com/questions/8013170/how-to-import-a-module-from-a-folder-next-to-the-current-folder

sys.path.insert(0,
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from src import db
from src.models import Film

del sys.path[0]
Нічого не зрозумів, але спрацювало

**Comment by alvasnet** [comment]
1. У мене підсистема Лінукс у Віндовс 10.
2. Коли запускаю основний файл проекта **pipenv run python wsgi.py** , то знаходить все коректно
3. А при запускі **pipenv run python src/inserts.py** знадобився цей хак

**Comment by vromanuk** [comment]
Как я понимаю, то проблема из-за того, что запуск команды происходит из корня, а внутри файла ожидается, что будет запускаться из src, если перейти внутрь src и оттуда запустить, то ошибки не должно быть.
